/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as MasterLoginRouteImport } from './routes/master-login'
import { Route as AuthenticatedMasterRouteImport } from './routes/_authenticated/master'
import { Route as AuthenticatedPainelRouteImport } from './routes/_authenticated/painel'
import { Route as AgendarSlugRouteImport } from './routes/agendar.$slug'
import { Route as AuthenticatedPainelIndexRouteImport } from './routes/_authenticated/painel.index'
import { Route as AuthenticatedPainelAsPayRouteImport } from './routes/_authenticated/painel.as-pay'
import { Route as AuthenticatedPainelBloqueiosRouteImport } from './routes/_authenticated/painel.bloqueios'
import { Route as AuthenticatedPainelCaixaRouteImport } from './routes/_authenticated/painel.caixa'
import { Route as AuthenticatedPainelClientesRouteImport } from './routes/_authenticated/painel.clientes'
import { Route as AuthenticatedPainelConfiguracoesRouteImport } from './routes/_authenticated/painel.configuracoes'
import { Route as AuthenticatedPainelFuncionamentoRouteImport } from './routes/_authenticated/painel.funcionamento'
import { Route as AuthenticatedPainelIntegracoesRouteImport } from './routes/_authenticated/painel.integracoes'
import { Route as AuthenticatedPainelLembretesRouteImport } from './routes/_authenticated/painel.lembretes'
import { Route as AuthenticatedPainelNegociosRouteImport } from './routes/_authenticated/painel.negocios'
import { Route as AuthenticatedPainelPagamentosRouteImport } from './routes/_authenticated/painel.pagamentos'
import { Route as AuthenticatedPainelProdutosRouteImport } from './routes/_authenticated/painel.produtos'
import { Route as AuthenticatedPainelProfissionaisRouteImport } from './routes/_authenticated/painel.profissionais'
import { Route as AuthenticatedPainelRelatorioRouteImport } from './routes/_authenticated/painel.relatorio'
import { Route as AuthenticatedPainelServicosRouteImport } from './routes/_authenticated/painel.servicos'
import { Route as AuthenticatedPainelTemplatesRouteImport } from './routes/_authenticated/painel.templates'
import { Route as AuthenticatedPainelWhatsappRouteImport } from './routes/_authenticated/painel.whatsapp'
import { Route as ApiPublicMercadopagoWebhookRouteImport } from './routes/api/public/mercadopago-webhook'
import { Route as ApiPublicHooksWhatsappRemindersRouteImport } from './routes/api/public/hooks/whatsapp-reminders'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterLoginRoute = MasterLoginRouteImport.update({
  id: '/master-login',
  path: '/master-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMasterRoute = AuthenticatedMasterRouteImport.update({
  id: '/master',
  path: '/master',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPainelRoute = AuthenticatedPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AgendarSlugRoute = AgendarSlugRouteImport.update({
  id: '/agendar/$slug',
  path: '/agendar/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPainelIndexRoute =
  AuthenticatedPainelIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const AuthenticatedPainelAsPayRoute =
  AuthenticatedPainelAsPayRouteImport.update({
    id: '/as-pay',
    path: '/as-pay',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const AuthenticatedPainelBloqueiosRoute =
  AuthenticatedPainelBloqueiosRouteImport.update({
    id: '/bloqueios',
    path: '/bloqueios',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const AuthenticatedPainelCaixaRoute =
  AuthenticatedPainelCaixaRouteImport.update({
    id: '/caixa',
    path: '/caixa',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const AuthenticatedPainelClientesRoute =
  AuthenticatedPainelClientesRouteImport.update({
    id: '/clientes',
    path: '/clientes',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const AuthenticatedPainelConfiguracoesRoute =
  AuthenticatedPainelConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const AuthenticatedPainelFuncionamentoRoute =
  AuthenticatedPainelFuncionamentoRouteImport.update({
    id: '/funcionamento',
    path: '/funcionamento',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const AuthenticatedPainelIntegracoesRoute =
  AuthenticatedPainelIntegracoesRouteImport.update({
    id: '/integracoes',
    path: '/integracoes',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const AuthenticatedPainelLembretesRoute =
  AuthenticatedPainelLembretesRouteImport.update({
    id: '/lembretes',
    path: '/lembretes',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const AuthenticatedPainelNegociosRoute =
  AuthenticatedPainelNegociosRouteImport.update({
    id: '/negocios',
    path: '/negocios',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const AuthenticatedPainelPagamentosRoute =
  AuthenticatedPainelPagamentosRouteImport.update({
    id: '/pagamentos',
    path: '/pagamentos',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const AuthenticatedPainelProdutosRoute =
  AuthenticatedPainelProdutosRouteImport.update({
    id: '/produtos',
    path: '/produtos',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const AuthenticatedPainelProfissionaisRoute =
  AuthenticatedPainelProfissionaisRouteImport.update({
    id: '/profissionais',
    path: '/profissionais',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const AuthenticatedPainelRelatorioRoute =
  AuthenticatedPainelRelatorioRouteImport.update({
    id: '/relatorio',
    path: '/relatorio',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const AuthenticatedPainelServicosRoute =
  AuthenticatedPainelServicosRouteImport.update({
    id: '/servicos',
    path: '/servicos',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const AuthenticatedPainelTemplatesRoute =
  AuthenticatedPainelTemplatesRouteImport.update({
    id: '/templates',
    path: '/templates',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const AuthenticatedPainelWhatsappRoute =
  AuthenticatedPainelWhatsappRouteImport.update({
    id: '/whatsapp',
    path: '/whatsapp',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const ApiPublicMercadopagoWebhookRoute =
  ApiPublicMercadopagoWebhookRouteImport.update({
    id: '/api/public/mercadopago-webhook',
    path: '/api/public/mercadopago-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksWhatsappRemindersRoute =
  ApiPublicHooksWhatsappRemindersRouteImport.update({
    id: '/api/public/hooks/whatsapp-reminders',
    path: '/api/public/hooks/whatsapp-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/master-login': typeof MasterLoginRoute
  '/master': typeof AuthenticatedMasterRoute
  '/painel': typeof AuthenticatedPainelRouteWithChildren
  '/agendar/$slug': typeof AgendarSlugRoute
  '/painel/as-pay': typeof AuthenticatedPainelAsPayRoute
  '/painel/bloqueios': typeof AuthenticatedPainelBloqueiosRoute
  '/painel/caixa': typeof AuthenticatedPainelCaixaRoute
  '/painel/clientes': typeof AuthenticatedPainelClientesRoute
  '/painel/configuracoes': typeof AuthenticatedPainelConfiguracoesRoute
  '/painel/funcionamento': typeof AuthenticatedPainelFuncionamentoRoute
  '/painel/integracoes': typeof AuthenticatedPainelIntegracoesRoute
  '/painel/lembretes': typeof AuthenticatedPainelLembretesRoute
  '/painel/negocios': typeof AuthenticatedPainelNegociosRoute
  '/painel/pagamentos': typeof AuthenticatedPainelPagamentosRoute
  '/painel/produtos': typeof AuthenticatedPainelProdutosRoute
  '/painel/profissionais': typeof AuthenticatedPainelProfissionaisRoute
  '/painel/relatorio': typeof AuthenticatedPainelRelatorioRoute
  '/painel/servicos': typeof AuthenticatedPainelServicosRoute
  '/painel/templates': typeof AuthenticatedPainelTemplatesRoute
  '/painel/whatsapp': typeof AuthenticatedPainelWhatsappRoute
  '/api/public/mercadopago-webhook': typeof ApiPublicMercadopagoWebhookRoute
  '/painel/': typeof AuthenticatedPainelIndexRoute
  '/api/public/hooks/whatsapp-reminders': typeof ApiPublicHooksWhatsappRemindersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/master-login': typeof MasterLoginRoute
  '/master': typeof AuthenticatedMasterRoute
  '/agendar/$slug': typeof AgendarSlugRoute
  '/painel/as-pay': typeof AuthenticatedPainelAsPayRoute
  '/painel/bloqueios': typeof AuthenticatedPainelBloqueiosRoute
  '/painel/caixa': typeof AuthenticatedPainelCaixaRoute
  '/painel/clientes': typeof AuthenticatedPainelClientesRoute
  '/painel/configuracoes': typeof AuthenticatedPainelConfiguracoesRoute
  '/painel/funcionamento': typeof AuthenticatedPainelFuncionamentoRoute
  '/painel/integracoes': typeof AuthenticatedPainelIntegracoesRoute
  '/painel/lembretes': typeof AuthenticatedPainelLembretesRoute
  '/painel/negocios': typeof AuthenticatedPainelNegociosRoute
  '/painel/pagamentos': typeof AuthenticatedPainelPagamentosRoute
  '/painel/produtos': typeof AuthenticatedPainelProdutosRoute
  '/painel/profissionais': typeof AuthenticatedPainelProfissionaisRoute
  '/painel/relatorio': typeof AuthenticatedPainelRelatorioRoute
  '/painel/servicos': typeof AuthenticatedPainelServicosRoute
  '/painel/templates': typeof AuthenticatedPainelTemplatesRoute
  '/painel/whatsapp': typeof AuthenticatedPainelWhatsappRoute
  '/api/public/mercadopago-webhook': typeof ApiPublicMercadopagoWebhookRoute
  '/painel': typeof AuthenticatedPainelIndexRoute
  '/api/public/hooks/whatsapp-reminders': typeof ApiPublicHooksWhatsappRemindersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/master-login': typeof MasterLoginRoute
  '/_authenticated/master': typeof AuthenticatedMasterRoute
  '/_authenticated/painel': typeof AuthenticatedPainelRouteWithChildren
  '/agendar/$slug': typeof AgendarSlugRoute
  '/_authenticated/painel/as-pay': typeof AuthenticatedPainelAsPayRoute
  '/_authenticated/painel/bloqueios': typeof AuthenticatedPainelBloqueiosRoute
  '/_authenticated/painel/caixa': typeof AuthenticatedPainelCaixaRoute
  '/_authenticated/painel/clientes': typeof AuthenticatedPainelClientesRoute
  '/_authenticated/painel/configuracoes': typeof AuthenticatedPainelConfiguracoesRoute
  '/_authenticated/painel/funcionamento': typeof AuthenticatedPainelFuncionamentoRoute
  '/_authenticated/painel/integracoes': typeof AuthenticatedPainelIntegracoesRoute
  '/_authenticated/painel/lembretes': typeof AuthenticatedPainelLembretesRoute
  '/_authenticated/painel/negocios': typeof AuthenticatedPainelNegociosRoute
  '/_authenticated/painel/pagamentos': typeof AuthenticatedPainelPagamentosRoute
  '/_authenticated/painel/produtos': typeof AuthenticatedPainelProdutosRoute
  '/_authenticated/painel/profissionais': typeof AuthenticatedPainelProfissionaisRoute
  '/_authenticated/painel/relatorio': typeof AuthenticatedPainelRelatorioRoute
  '/_authenticated/painel/servicos': typeof AuthenticatedPainelServicosRoute
  '/_authenticated/painel/templates': typeof AuthenticatedPainelTemplatesRoute
  '/_authenticated/painel/whatsapp': typeof AuthenticatedPainelWhatsappRoute
  '/api/public/mercadopago-webhook': typeof ApiPublicMercadopagoWebhookRoute
  '/_authenticated/painel/': typeof AuthenticatedPainelIndexRoute
  '/api/public/hooks/whatsapp-reminders': typeof ApiPublicHooksWhatsappRemindersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/master-login'
    | '/master'
    | '/painel'
    | '/agendar/$slug'
    | '/painel/as-pay'
    | '/painel/bloqueios'
    | '/painel/caixa'
    | '/painel/clientes'
    | '/painel/configuracoes'
    | '/painel/funcionamento'
    | '/painel/integracoes'
    | '/painel/lembretes'
    | '/painel/negocios'
    | '/painel/pagamentos'
    | '/painel/produtos'
    | '/painel/profissionais'
    | '/painel/relatorio'
    | '/painel/servicos'
    | '/painel/templates'
    | '/painel/whatsapp'
    | '/api/public/mercadopago-webhook'
    | '/painel/'
    | '/api/public/hooks/whatsapp-reminders'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/master-login'
    | '/master'
    | '/agendar/$slug'
    | '/painel/as-pay'
    | '/painel/bloqueios'
    | '/painel/caixa'
    | '/painel/clientes'
    | '/painel/configuracoes'
    | '/painel/funcionamento'
    | '/painel/integracoes'
    | '/painel/lembretes'
    | '/painel/negocios'
    | '/painel/pagamentos'
    | '/painel/produtos'
    | '/painel/profissionais'
    | '/painel/relatorio'
    | '/painel/servicos'
    | '/painel/templates'
    | '/painel/whatsapp'
    | '/api/public/mercadopago-webhook'
    | '/painel'
    | '/api/public/hooks/whatsapp-reminders'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/master-login'
    | '/_authenticated/master'
    | '/_authenticated/painel'
    | '/agendar/$slug'
    | '/_authenticated/painel/as-pay'
    | '/_authenticated/painel/bloqueios'
    | '/_authenticated/painel/caixa'
    | '/_authenticated/painel/clientes'
    | '/_authenticated/painel/configuracoes'
    | '/_authenticated/painel/funcionamento'
    | '/_authenticated/painel/integracoes'
    | '/_authenticated/painel/lembretes'
    | '/_authenticated/painel/negocios'
    | '/_authenticated/painel/pagamentos'
    | '/_authenticated/painel/produtos'
    | '/_authenticated/painel/profissionais'
    | '/_authenticated/painel/relatorio'
    | '/_authenticated/painel/servicos'
    | '/_authenticated/painel/templates'
    | '/_authenticated/painel/whatsapp'
    | '/api/public/mercadopago-webhook'
    | '/_authenticated/painel/'
    | '/api/public/hooks/whatsapp-reminders'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  MasterLoginRoute: typeof MasterLoginRoute
  AgendarSlugRoute: typeof AgendarSlugRoute
  ApiPublicMercadopagoWebhookRoute: typeof ApiPublicMercadopagoWebhookRoute
  ApiPublicHooksWhatsappRemindersRoute: typeof ApiPublicHooksWhatsappRemindersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master-login': {
      id: '/master-login'
      path: '/master-login'
      fullPath: '/master-login'
      preLoaderRoute: typeof MasterLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/master': {
      id: '/_authenticated/master'
      path: '/master'
      fullPath: '/master'
      preLoaderRoute: typeof AuthenticatedMasterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel': {
      id: '/_authenticated/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AuthenticatedPainelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/agendar/$slug': {
      id: '/agendar/$slug'
      path: '/agendar/$slug'
      fullPath: '/agendar/$slug'
      preLoaderRoute: typeof AgendarSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/painel/': {
      id: '/_authenticated/painel/'
      path: '/'
      fullPath: '/painel/'
      preLoaderRoute: typeof AuthenticatedPainelIndexRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/painel/as-pay': {
      id: '/_authenticated/painel/as-pay'
      path: '/as-pay'
      fullPath: '/painel/as-pay'
      preLoaderRoute: typeof AuthenticatedPainelAsPayRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/painel/bloqueios': {
      id: '/_authenticated/painel/bloqueios'
      path: '/bloqueios'
      fullPath: '/painel/bloqueios'
      preLoaderRoute: typeof AuthenticatedPainelBloqueiosRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/painel/caixa': {
      id: '/_authenticated/painel/caixa'
      path: '/caixa'
      fullPath: '/painel/caixa'
      preLoaderRoute: typeof AuthenticatedPainelCaixaRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/painel/clientes': {
      id: '/_authenticated/painel/clientes'
      path: '/clientes'
      fullPath: '/painel/clientes'
      preLoaderRoute: typeof AuthenticatedPainelClientesRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/painel/configuracoes': {
      id: '/_authenticated/painel/configuracoes'
      path: '/configuracoes'
      fullPath: '/painel/configuracoes'
      preLoaderRoute: typeof AuthenticatedPainelConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/painel/funcionamento': {
      id: '/_authenticated/painel/funcionamento'
      path: '/funcionamento'
      fullPath: '/painel/funcionamento'
      preLoaderRoute: typeof AuthenticatedPainelFuncionamentoRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/painel/integracoes': {
      id: '/_authenticated/painel/integracoes'
      path: '/integracoes'
      fullPath: '/painel/integracoes'
      preLoaderRoute: typeof AuthenticatedPainelIntegracoesRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/painel/lembretes': {
      id: '/_authenticated/painel/lembretes'
      path: '/lembretes'
      fullPath: '/painel/lembretes'
      preLoaderRoute: typeof AuthenticatedPainelLembretesRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/painel/negocios': {
      id: '/_authenticated/painel/negocios'
      path: '/negocios'
      fullPath: '/painel/negocios'
      preLoaderRoute: typeof AuthenticatedPainelNegociosRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/painel/pagamentos': {
      id: '/_authenticated/painel/pagamentos'
      path: '/pagamentos'
      fullPath: '/painel/pagamentos'
      preLoaderRoute: typeof AuthenticatedPainelPagamentosRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/painel/produtos': {
      id: '/_authenticated/painel/produtos'
      path: '/produtos'
      fullPath: '/painel/produtos'
      preLoaderRoute: typeof AuthenticatedPainelProdutosRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/painel/profissionais': {
      id: '/_authenticated/painel/profissionais'
      path: '/profissionais'
      fullPath: '/painel/profissionais'
      preLoaderRoute: typeof AuthenticatedPainelProfissionaisRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/painel/relatorio': {
      id: '/_authenticated/painel/relatorio'
      path: '/relatorio'
      fullPath: '/painel/relatorio'
      preLoaderRoute: typeof AuthenticatedPainelRelatorioRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/painel/servicos': {
      id: '/_authenticated/painel/servicos'
      path: '/servicos'
      fullPath: '/painel/servicos'
      preLoaderRoute: typeof AuthenticatedPainelServicosRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/painel/templates': {
      id: '/_authenticated/painel/templates'
      path: '/templates'
      fullPath: '/painel/templates'
      preLoaderRoute: typeof AuthenticatedPainelTemplatesRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/painel/whatsapp': {
      id: '/_authenticated/painel/whatsapp'
      path: '/whatsapp'
      fullPath: '/painel/whatsapp'
      preLoaderRoute: typeof AuthenticatedPainelWhatsappRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/api/public/mercadopago-webhook': {
      id: '/api/public/mercadopago-webhook'
      path: '/api/public/mercadopago-webhook'
      fullPath: '/api/public/mercadopago-webhook'
      preLoaderRoute: typeof ApiPublicMercadopagoWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/whatsapp-reminders': {
      id: '/api/public/hooks/whatsapp-reminders'
      path: '/api/public/hooks/whatsapp-reminders'
      fullPath: '/api/public/hooks/whatsapp-reminders'
      preLoaderRoute: typeof ApiPublicHooksWhatsappRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedPainelRouteChildren {
  AuthenticatedPainelAsPayRoute: typeof AuthenticatedPainelAsPayRoute
  AuthenticatedPainelBloqueiosRoute: typeof AuthenticatedPainelBloqueiosRoute
  AuthenticatedPainelCaixaRoute: typeof AuthenticatedPainelCaixaRoute
  AuthenticatedPainelClientesRoute: typeof AuthenticatedPainelClientesRoute
  AuthenticatedPainelConfiguracoesRoute: typeof AuthenticatedPainelConfiguracoesRoute
  AuthenticatedPainelFuncionamentoRoute: typeof AuthenticatedPainelFuncionamentoRoute
  AuthenticatedPainelIntegracoesRoute: typeof AuthenticatedPainelIntegracoesRoute
  AuthenticatedPainelLembretesRoute: typeof AuthenticatedPainelLembretesRoute
  AuthenticatedPainelNegociosRoute: typeof AuthenticatedPainelNegociosRoute
  AuthenticatedPainelPagamentosRoute: typeof AuthenticatedPainelPagamentosRoute
  AuthenticatedPainelProdutosRoute: typeof AuthenticatedPainelProdutosRoute
  AuthenticatedPainelProfissionaisRoute: typeof AuthenticatedPainelProfissionaisRoute
  AuthenticatedPainelRelatorioRoute: typeof AuthenticatedPainelRelatorioRoute
  AuthenticatedPainelServicosRoute: typeof AuthenticatedPainelServicosRoute
  AuthenticatedPainelTemplatesRoute: typeof AuthenticatedPainelTemplatesRoute
  AuthenticatedPainelWhatsappRoute: typeof AuthenticatedPainelWhatsappRoute
  AuthenticatedPainelIndexRoute: typeof AuthenticatedPainelIndexRoute
}

const AuthenticatedPainelRouteChildren: AuthenticatedPainelRouteChildren = {
  AuthenticatedPainelAsPayRoute: AuthenticatedPainelAsPayRoute,
  AuthenticatedPainelBloqueiosRoute: AuthenticatedPainelBloqueiosRoute,
  AuthenticatedPainelCaixaRoute: AuthenticatedPainelCaixaRoute,
  AuthenticatedPainelClientesRoute: AuthenticatedPainelClientesRoute,
  AuthenticatedPainelConfiguracoesRoute: AuthenticatedPainelConfiguracoesRoute,
  AuthenticatedPainelFuncionamentoRoute: AuthenticatedPainelFuncionamentoRoute,
  AuthenticatedPainelIntegracoesRoute: AuthenticatedPainelIntegracoesRoute,
  AuthenticatedPainelLembretesRoute: AuthenticatedPainelLembretesRoute,
  AuthenticatedPainelNegociosRoute: AuthenticatedPainelNegociosRoute,
  AuthenticatedPainelPagamentosRoute: AuthenticatedPainelPagamentosRoute,
  AuthenticatedPainelProdutosRoute: AuthenticatedPainelProdutosRoute,
  AuthenticatedPainelProfissionaisRoute: AuthenticatedPainelProfissionaisRoute,
  AuthenticatedPainelRelatorioRoute: AuthenticatedPainelRelatorioRoute,
  AuthenticatedPainelServicosRoute: AuthenticatedPainelServicosRoute,
  AuthenticatedPainelTemplatesRoute: AuthenticatedPainelTemplatesRoute,
  AuthenticatedPainelWhatsappRoute: AuthenticatedPainelWhatsappRoute,
  AuthenticatedPainelIndexRoute: AuthenticatedPainelIndexRoute,
}

const AuthenticatedPainelRouteWithChildren =
  AuthenticatedPainelRoute._addFileChildren(AuthenticatedPainelRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedMasterRoute: typeof AuthenticatedMasterRoute
  AuthenticatedPainelRoute: typeof AuthenticatedPainelRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedMasterRoute: AuthenticatedMasterRoute,
  AuthenticatedPainelRoute: AuthenticatedPainelRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  MasterLoginRoute: MasterLoginRoute,
  AgendarSlugRoute: AgendarSlugRoute,
  ApiPublicMercadopagoWebhookRoute: ApiPublicMercadopagoWebhookRoute,
  ApiPublicHooksWhatsappRemindersRoute: ApiPublicHooksWhatsappRemindersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
