/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedMasterRouteImport } from './routes/_authenticated/master'
import { Route as AuthenticatedPainelRouteImport } from './routes/_authenticated/painel'
import { Route as AgendarSlugRouteImport } from './routes/agendar.$slug'
import { Route as AuthenticatedEditorTemplateIdRouteImport } from './routes/_authenticated/editor-template.$id'
import { Route as AuthenticatedPainelIndexRouteImport } from './routes/_authenticated/painel.index'
import { Route as AuthenticatedPainelAparenciaEditorRouteImport } from './routes/_authenticated/painel.aparencia-editor'
import { Route as AuthenticatedPainelAsPayRouteImport } from './routes/_authenticated/painel.as-pay'
import { Route as AuthenticatedPainelBloqueiosRouteImport } from './routes/_authenticated/painel.bloqueios'
import { Route as AuthenticatedPainelClientesRouteImport } from './routes/_authenticated/painel.clientes'
import { Route as AuthenticatedPainelConfiguracoesRouteImport } from './routes/_authenticated/painel.configuracoes'
import { Route as AuthenticatedPainelFuncionamentoRouteImport } from './routes/_authenticated/painel.funcionamento'
import { Route as AuthenticatedPainelIntegracoesRouteImport } from './routes/_authenticated/painel.integracoes'
import { Route as AuthenticatedPainelLembretesRouteImport } from './routes/_authenticated/painel.lembretes'
import { Route as AuthenticatedPainelMasterRouteImport } from './routes/_authenticated/painel.master'
import { Route as AuthenticatedPainelNegociosRouteImport } from './routes/_authenticated/painel.negocios'
import { Route as AuthenticatedPainelProfissionaisRouteImport } from './routes/_authenticated/painel.profissionais'
import { Route as AuthenticatedPainelRelatorioRouteImport } from './routes/_authenticated/painel.relatorio'
import { Route as AuthenticatedPainelServicosRouteImport } from './routes/_authenticated/painel.servicos'
import { Route as AuthenticatedPainelTemplatesRouteImport } from './routes/_authenticated/painel.templates'
import { Route as ApiPublicAgpayWebhookRouteImport } from './routes/api/public/agpay-webhook'
import { Route as ApiPublicHooksAgpayEventsRouteImport } from './routes/api/public/hooks/agpay-events'
import { Route as ApiPublicHooksWhatsappRemindersRouteImport } from './routes/api/public/hooks/whatsapp-reminders'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMasterRoute = AuthenticatedMasterRouteImport.update({
  id: '/master',
  path: '/master',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPainelRoute = AuthenticatedPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AgendarSlugRoute = AgendarSlugRouteImport.update({
  id: '/agendar/$slug',
  path: '/agendar/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedEditorTemplateIdRoute =
  AuthenticatedEditorTemplateIdRouteImport.update({
    id: '/editor-template/$id',
    path: '/editor-template/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPainelIndexRoute =
  AuthenticatedPainelIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const AuthenticatedPainelAparenciaEditorRoute =
  AuthenticatedPainelAparenciaEditorRouteImport.update({
    id: '/aparencia-editor',
    path: '/aparencia-editor',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const AuthenticatedPainelAsPayRoute =
  AuthenticatedPainelAsPayRouteImport.update({
    id: '/as-pay',
    path: '/as-pay',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const AuthenticatedPainelBloqueiosRoute =
  AuthenticatedPainelBloqueiosRouteImport.update({
    id: '/bloqueios',
    path: '/bloqueios',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const AuthenticatedPainelClientesRoute =
  AuthenticatedPainelClientesRouteImport.update({
    id: '/clientes',
    path: '/clientes',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const AuthenticatedPainelConfiguracoesRoute =
  AuthenticatedPainelConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const AuthenticatedPainelFuncionamentoRoute =
  AuthenticatedPainelFuncionamentoRouteImport.update({
    id: '/funcionamento',
    path: '/funcionamento',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const AuthenticatedPainelIntegracoesRoute =
  AuthenticatedPainelIntegracoesRouteImport.update({
    id: '/integracoes',
    path: '/integracoes',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const AuthenticatedPainelLembretesRoute =
  AuthenticatedPainelLembretesRouteImport.update({
    id: '/lembretes',
    path: '/lembretes',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const AuthenticatedPainelMasterRoute =
  AuthenticatedPainelMasterRouteImport.update({
    id: '/master',
    path: '/master',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const AuthenticatedPainelNegociosRoute =
  AuthenticatedPainelNegociosRouteImport.update({
    id: '/negocios',
    path: '/negocios',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const AuthenticatedPainelProfissionaisRoute =
  AuthenticatedPainelProfissionaisRouteImport.update({
    id: '/profissionais',
    path: '/profissionais',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const AuthenticatedPainelRelatorioRoute =
  AuthenticatedPainelRelatorioRouteImport.update({
    id: '/relatorio',
    path: '/relatorio',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const AuthenticatedPainelServicosRoute =
  AuthenticatedPainelServicosRouteImport.update({
    id: '/servicos',
    path: '/servicos',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const AuthenticatedPainelTemplatesRoute =
  AuthenticatedPainelTemplatesRouteImport.update({
    id: '/templates',
    path: '/templates',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const ApiPublicAgpayWebhookRoute = ApiPublicAgpayWebhookRouteImport.update({
  id: '/api/public/agpay-webhook',
  path: '/api/public/agpay-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksAgpayEventsRoute =
  ApiPublicHooksAgpayEventsRouteImport.update({
    id: '/api/public/hooks/agpay-events',
    path: '/api/public/hooks/agpay-events',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksWhatsappRemindersRoute =
  ApiPublicHooksWhatsappRemindersRouteImport.update({
    id: '/api/public/hooks/whatsapp-reminders',
    path: '/api/public/hooks/whatsapp-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/master': typeof AuthenticatedMasterRoute
  '/painel': typeof AuthenticatedPainelRouteWithChildren
  '/agendar/$slug': typeof AgendarSlugRoute
  '/editor-template/$id': typeof AuthenticatedEditorTemplateIdRoute
  '/painel/aparencia-editor': typeof AuthenticatedPainelAparenciaEditorRoute
  '/painel/as-pay': typeof AuthenticatedPainelAsPayRoute
  '/painel/bloqueios': typeof AuthenticatedPainelBloqueiosRoute
  '/painel/clientes': typeof AuthenticatedPainelClientesRoute
  '/painel/configuracoes': typeof AuthenticatedPainelConfiguracoesRoute
  '/painel/funcionamento': typeof AuthenticatedPainelFuncionamentoRoute
  '/painel/integracoes': typeof AuthenticatedPainelIntegracoesRoute
  '/painel/lembretes': typeof AuthenticatedPainelLembretesRoute
  '/painel/master': typeof AuthenticatedPainelMasterRoute
  '/painel/negocios': typeof AuthenticatedPainelNegociosRoute
  '/painel/profissionais': typeof AuthenticatedPainelProfissionaisRoute
  '/painel/relatorio': typeof AuthenticatedPainelRelatorioRoute
  '/painel/servicos': typeof AuthenticatedPainelServicosRoute
  '/painel/templates': typeof AuthenticatedPainelTemplatesRoute
  '/api/public/agpay-webhook': typeof ApiPublicAgpayWebhookRoute
  '/painel/': typeof AuthenticatedPainelIndexRoute
  '/api/public/hooks/agpay-events': typeof ApiPublicHooksAgpayEventsRoute
  '/api/public/hooks/whatsapp-reminders': typeof ApiPublicHooksWhatsappRemindersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/master': typeof AuthenticatedMasterRoute
  '/agendar/$slug': typeof AgendarSlugRoute
  '/editor-template/$id': typeof AuthenticatedEditorTemplateIdRoute
  '/painel/aparencia-editor': typeof AuthenticatedPainelAparenciaEditorRoute
  '/painel/as-pay': typeof AuthenticatedPainelAsPayRoute
  '/painel/bloqueios': typeof AuthenticatedPainelBloqueiosRoute
  '/painel/clientes': typeof AuthenticatedPainelClientesRoute
  '/painel/configuracoes': typeof AuthenticatedPainelConfiguracoesRoute
  '/painel/funcionamento': typeof AuthenticatedPainelFuncionamentoRoute
  '/painel/integracoes': typeof AuthenticatedPainelIntegracoesRoute
  '/painel/lembretes': typeof AuthenticatedPainelLembretesRoute
  '/painel/master': typeof AuthenticatedPainelMasterRoute
  '/painel/negocios': typeof AuthenticatedPainelNegociosRoute
  '/painel/profissionais': typeof AuthenticatedPainelProfissionaisRoute
  '/painel/relatorio': typeof AuthenticatedPainelRelatorioRoute
  '/painel/servicos': typeof AuthenticatedPainelServicosRoute
  '/painel/templates': typeof AuthenticatedPainelTemplatesRoute
  '/api/public/agpay-webhook': typeof ApiPublicAgpayWebhookRoute
  '/painel': typeof AuthenticatedPainelIndexRoute
  '/api/public/hooks/agpay-events': typeof ApiPublicHooksAgpayEventsRoute
  '/api/public/hooks/whatsapp-reminders': typeof ApiPublicHooksWhatsappRemindersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/master': typeof AuthenticatedMasterRoute
  '/_authenticated/painel': typeof AuthenticatedPainelRouteWithChildren
  '/agendar/$slug': typeof AgendarSlugRoute
  '/_authenticated/editor-template/$id': typeof AuthenticatedEditorTemplateIdRoute
  '/_authenticated/painel/aparencia-editor': typeof AuthenticatedPainelAparenciaEditorRoute
  '/_authenticated/painel/as-pay': typeof AuthenticatedPainelAsPayRoute
  '/_authenticated/painel/bloqueios': typeof AuthenticatedPainelBloqueiosRoute
  '/_authenticated/painel/clientes': typeof AuthenticatedPainelClientesRoute
  '/_authenticated/painel/configuracoes': typeof AuthenticatedPainelConfiguracoesRoute
  '/_authenticated/painel/funcionamento': typeof AuthenticatedPainelFuncionamentoRoute
  '/_authenticated/painel/integracoes': typeof AuthenticatedPainelIntegracoesRoute
  '/_authenticated/painel/lembretes': typeof AuthenticatedPainelLembretesRoute
  '/_authenticated/painel/master': typeof AuthenticatedPainelMasterRoute
  '/_authenticated/painel/negocios': typeof AuthenticatedPainelNegociosRoute
  '/_authenticated/painel/profissionais': typeof AuthenticatedPainelProfissionaisRoute
  '/_authenticated/painel/relatorio': typeof AuthenticatedPainelRelatorioRoute
  '/_authenticated/painel/servicos': typeof AuthenticatedPainelServicosRoute
  '/_authenticated/painel/templates': typeof AuthenticatedPainelTemplatesRoute
  '/api/public/agpay-webhook': typeof ApiPublicAgpayWebhookRoute
  '/_authenticated/painel/': typeof AuthenticatedPainelIndexRoute
  '/api/public/hooks/agpay-events': typeof ApiPublicHooksAgpayEventsRoute
  '/api/public/hooks/whatsapp-reminders': typeof ApiPublicHooksWhatsappRemindersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/master'
    | '/painel'
    | '/agendar/$slug'
    | '/editor-template/$id'
    | '/painel/aparencia-editor'
    | '/painel/as-pay'
    | '/painel/bloqueios'
    | '/painel/clientes'
    | '/painel/configuracoes'
    | '/painel/funcionamento'
    | '/painel/integracoes'
    | '/painel/lembretes'
    | '/painel/master'
    | '/painel/negocios'
    | '/painel/profissionais'
    | '/painel/relatorio'
    | '/painel/servicos'
    | '/painel/templates'
    | '/api/public/agpay-webhook'
    | '/painel/'
    | '/api/public/hooks/agpay-events'
    | '/api/public/hooks/whatsapp-reminders'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/master'
    | '/agendar/$slug'
    | '/editor-template/$id'
    | '/painel/aparencia-editor'
    | '/painel/as-pay'
    | '/painel/bloqueios'
    | '/painel/clientes'
    | '/painel/configuracoes'
    | '/painel/funcionamento'
    | '/painel/integracoes'
    | '/painel/lembretes'
    | '/painel/master'
    | '/painel/negocios'
    | '/painel/profissionais'
    | '/painel/relatorio'
    | '/painel/servicos'
    | '/painel/templates'
    | '/api/public/agpay-webhook'
    | '/painel'
    | '/api/public/hooks/agpay-events'
    | '/api/public/hooks/whatsapp-reminders'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/master'
    | '/_authenticated/painel'
    | '/agendar/$slug'
    | '/_authenticated/editor-template/$id'
    | '/_authenticated/painel/aparencia-editor'
    | '/_authenticated/painel/as-pay'
    | '/_authenticated/painel/bloqueios'
    | '/_authenticated/painel/clientes'
    | '/_authenticated/painel/configuracoes'
    | '/_authenticated/painel/funcionamento'
    | '/_authenticated/painel/integracoes'
    | '/_authenticated/painel/lembretes'
    | '/_authenticated/painel/master'
    | '/_authenticated/painel/negocios'
    | '/_authenticated/painel/profissionais'
    | '/_authenticated/painel/relatorio'
    | '/_authenticated/painel/servicos'
    | '/_authenticated/painel/templates'
    | '/api/public/agpay-webhook'
    | '/_authenticated/painel/'
    | '/api/public/hooks/agpay-events'
    | '/api/public/hooks/whatsapp-reminders'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  AgendarSlugRoute: typeof AgendarSlugRoute
  ApiPublicAgpayWebhookRoute: typeof ApiPublicAgpayWebhookRoute
  ApiPublicHooksAgpayEventsRoute: typeof ApiPublicHooksAgpayEventsRoute
  ApiPublicHooksWhatsappRemindersRoute: typeof ApiPublicHooksWhatsappRemindersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/master': {
      id: '/_authenticated/master'
      path: '/master'
      fullPath: '/master'
      preLoaderRoute: typeof AuthenticatedMasterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel': {
      id: '/_authenticated/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AuthenticatedPainelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/agendar/$slug': {
      id: '/agendar/$slug'
      path: '/agendar/$slug'
      fullPath: '/agendar/$slug'
      preLoaderRoute: typeof AgendarSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/editor-template/$id': {
      id: '/_authenticated/editor-template/$id'
      path: '/editor-template/$id'
      fullPath: '/editor-template/$id'
      preLoaderRoute: typeof AuthenticatedEditorTemplateIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel/': {
      id: '/_authenticated/painel/'
      path: '/'
      fullPath: '/painel/'
      preLoaderRoute: typeof AuthenticatedPainelIndexRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/painel/aparencia-editor': {
      id: '/_authenticated/painel/aparencia-editor'
      path: '/aparencia-editor'
      fullPath: '/painel/aparencia-editor'
      preLoaderRoute: typeof AuthenticatedPainelAparenciaEditorRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/painel/as-pay': {
      id: '/_authenticated/painel/as-pay'
      path: '/as-pay'
      fullPath: '/painel/as-pay'
      preLoaderRoute: typeof AuthenticatedPainelAsPayRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/painel/bloqueios': {
      id: '/_authenticated/painel/bloqueios'
      path: '/bloqueios'
      fullPath: '/painel/bloqueios'
      preLoaderRoute: typeof AuthenticatedPainelBloqueiosRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/painel/clientes': {
      id: '/_authenticated/painel/clientes'
      path: '/clientes'
      fullPath: '/painel/clientes'
      preLoaderRoute: typeof AuthenticatedPainelClientesRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/painel/configuracoes': {
      id: '/_authenticated/painel/configuracoes'
      path: '/configuracoes'
      fullPath: '/painel/configuracoes'
      preLoaderRoute: typeof AuthenticatedPainelConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/painel/funcionamento': {
      id: '/_authenticated/painel/funcionamento'
      path: '/funcionamento'
      fullPath: '/painel/funcionamento'
      preLoaderRoute: typeof AuthenticatedPainelFuncionamentoRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/painel/integracoes': {
      id: '/_authenticated/painel/integracoes'
      path: '/integracoes'
      fullPath: '/painel/integracoes'
      preLoaderRoute: typeof AuthenticatedPainelIntegracoesRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/painel/lembretes': {
      id: '/_authenticated/painel/lembretes'
      path: '/lembretes'
      fullPath: '/painel/lembretes'
      preLoaderRoute: typeof AuthenticatedPainelLembretesRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/painel/master': {
      id: '/_authenticated/painel/master'
      path: '/master'
      fullPath: '/painel/master'
      preLoaderRoute: typeof AuthenticatedPainelMasterRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/painel/negocios': {
      id: '/_authenticated/painel/negocios'
      path: '/negocios'
      fullPath: '/painel/negocios'
      preLoaderRoute: typeof AuthenticatedPainelNegociosRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/painel/profissionais': {
      id: '/_authenticated/painel/profissionais'
      path: '/profissionais'
      fullPath: '/painel/profissionais'
      preLoaderRoute: typeof AuthenticatedPainelProfissionaisRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/painel/relatorio': {
      id: '/_authenticated/painel/relatorio'
      path: '/relatorio'
      fullPath: '/painel/relatorio'
      preLoaderRoute: typeof AuthenticatedPainelRelatorioRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/painel/servicos': {
      id: '/_authenticated/painel/servicos'
      path: '/servicos'
      fullPath: '/painel/servicos'
      preLoaderRoute: typeof AuthenticatedPainelServicosRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/painel/templates': {
      id: '/_authenticated/painel/templates'
      path: '/templates'
      fullPath: '/painel/templates'
      preLoaderRoute: typeof AuthenticatedPainelTemplatesRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/api/public/agpay-webhook': {
      id: '/api/public/agpay-webhook'
      path: '/api/public/agpay-webhook'
      fullPath: '/api/public/agpay-webhook'
      preLoaderRoute: typeof ApiPublicAgpayWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/agpay-events': {
      id: '/api/public/hooks/agpay-events'
      path: '/api/public/hooks/agpay-events'
      fullPath: '/api/public/hooks/agpay-events'
      preLoaderRoute: typeof ApiPublicHooksAgpayEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/whatsapp-reminders': {
      id: '/api/public/hooks/whatsapp-reminders'
      path: '/api/public/hooks/whatsapp-reminders'
      fullPath: '/api/public/hooks/whatsapp-reminders'
      preLoaderRoute: typeof ApiPublicHooksWhatsappRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedPainelRouteChildren {
  AuthenticatedPainelAparenciaEditorRoute: typeof AuthenticatedPainelAparenciaEditorRoute
  AuthenticatedPainelAsPayRoute: typeof AuthenticatedPainelAsPayRoute
  AuthenticatedPainelBloqueiosRoute: typeof AuthenticatedPainelBloqueiosRoute
  AuthenticatedPainelClientesRoute: typeof AuthenticatedPainelClientesRoute
  AuthenticatedPainelConfiguracoesRoute: typeof AuthenticatedPainelConfiguracoesRoute
  AuthenticatedPainelFuncionamentoRoute: typeof AuthenticatedPainelFuncionamentoRoute
  AuthenticatedPainelIntegracoesRoute: typeof AuthenticatedPainelIntegracoesRoute
  AuthenticatedPainelLembretesRoute: typeof AuthenticatedPainelLembretesRoute
  AuthenticatedPainelMasterRoute: typeof AuthenticatedPainelMasterRoute
  AuthenticatedPainelNegociosRoute: typeof AuthenticatedPainelNegociosRoute
  AuthenticatedPainelProfissionaisRoute: typeof AuthenticatedPainelProfissionaisRoute
  AuthenticatedPainelRelatorioRoute: typeof AuthenticatedPainelRelatorioRoute
  AuthenticatedPainelServicosRoute: typeof AuthenticatedPainelServicosRoute
  AuthenticatedPainelTemplatesRoute: typeof AuthenticatedPainelTemplatesRoute
  AuthenticatedPainelIndexRoute: typeof AuthenticatedPainelIndexRoute
}

const AuthenticatedPainelRouteChildren: AuthenticatedPainelRouteChildren = {
  AuthenticatedPainelAparenciaEditorRoute:
    AuthenticatedPainelAparenciaEditorRoute,
  AuthenticatedPainelAsPayRoute: AuthenticatedPainelAsPayRoute,
  AuthenticatedPainelBloqueiosRoute: AuthenticatedPainelBloqueiosRoute,
  AuthenticatedPainelClientesRoute: AuthenticatedPainelClientesRoute,
  AuthenticatedPainelConfiguracoesRoute: AuthenticatedPainelConfiguracoesRoute,
  AuthenticatedPainelFuncionamentoRoute: AuthenticatedPainelFuncionamentoRoute,
  AuthenticatedPainelIntegracoesRoute: AuthenticatedPainelIntegracoesRoute,
  AuthenticatedPainelLembretesRoute: AuthenticatedPainelLembretesRoute,
  AuthenticatedPainelMasterRoute: AuthenticatedPainelMasterRoute,
  AuthenticatedPainelNegociosRoute: AuthenticatedPainelNegociosRoute,
  AuthenticatedPainelProfissionaisRoute: AuthenticatedPainelProfissionaisRoute,
  AuthenticatedPainelRelatorioRoute: AuthenticatedPainelRelatorioRoute,
  AuthenticatedPainelServicosRoute: AuthenticatedPainelServicosRoute,
  AuthenticatedPainelTemplatesRoute: AuthenticatedPainelTemplatesRoute,
  AuthenticatedPainelIndexRoute: AuthenticatedPainelIndexRoute,
}

const AuthenticatedPainelRouteWithChildren =
  AuthenticatedPainelRoute._addFileChildren(AuthenticatedPainelRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedMasterRoute: typeof AuthenticatedMasterRoute
  AuthenticatedPainelRoute: typeof AuthenticatedPainelRouteWithChildren
  AuthenticatedEditorTemplateIdRoute: typeof AuthenticatedEditorTemplateIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedMasterRoute: AuthenticatedMasterRoute,
  AuthenticatedPainelRoute: AuthenticatedPainelRouteWithChildren,
  AuthenticatedEditorTemplateIdRoute: AuthenticatedEditorTemplateIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  AgendarSlugRoute: AgendarSlugRoute,
  ApiPublicAgpayWebhookRoute: ApiPublicAgpayWebhookRoute,
  ApiPublicHooksAgpayEventsRoute: ApiPublicHooksAgpayEventsRoute,
  ApiPublicHooksWhatsappRemindersRoute: ApiPublicHooksWhatsappRemindersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
