// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from "@tanstack/react-start";

function hasPersistedSupabaseSession() {
  if (typeof window === "undefined") return false;
  for (let index = 0; index < window.localStorage.length; index += 1) {
    const key = window.localStorage.key(index);
    if (key?.startsWith("sb-") && key.endsWith("-auth-token")) return true;
  }
  return false;
}

// Must be registered as a global `functionMiddleware` in `src/start.ts`; otherwise
// the browser never attaches the bearer token to serverFn RPCs.
export const attachSupabaseAuth = createMiddleware({ type: "function" }).client(
  async ({ next }) => {
    // Rotas públicas não precisam baixar/inicializar o SDK completo do Supabase.
    // Usuários autenticados sempre têm a sessão persistida pelo supabase-js.
    if (!hasPersistedSupabaseSession()) return next({ headers: {} });

    const { supabase } = await import("./client");
    const { data } = await supabase.auth.getSession();
    const token = data.session?.access_token;
    return next({
      headers: token ? { Authorization: `Bearer ${token}` } : {},
    });
  },
);
